// <auto-generated />
using DataModels.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataModels.Migrations
{
    [DbContext(typeof(OrigamiContext))]
    partial class OrigamiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("DataModels.Model.Origami", b =>
                {
                    b.Property<int>("OrigamiId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Avatar");

                    b.Property<string>("Introduce");

                    b.Property<string>("MovieUrl");

                    b.Property<string>("Name");

                    b.Property<string>("PicList");

                    b.Property<int>("Status");

                    b.Property<string>("Title");

                    b.Property<int>("Type");

                    b.HasKey("OrigamiId");

                    b.ToTable("origamis");
                });
#pragma warning restore 612, 618
        }
    }
}
